const LAT=27.202, LON=73.7339, R=100;const OM='https://api.open-meteo.com/v1/forecast';const IMD='https://mausam.imd.gov.in/api/';let map,radarLayers=[],weather=null;
const $=id=>document.getElementById(id), n=v=>Number.isFinite(Number(v))?Number(v):0, mm=v=>n(v).toFixed(1);
async function getJSON(url,opt={}){const c=new AbortController(),t=setTimeout(()=>c.abort(),12000);try{const r=await fetch(url,{...opt,signal:c.signal,cache:'no-store'});if(!r.ok)throw Error(r.status);return await r.json()}finally{clearTimeout(t)}}
function cards(d){const c=d.current||{},h=d.hourly||{},i=0;const vals=[['🌧️ Rain now',mm(c.precipitation)+' mm'],['💧 Rain chance',n(h.precipitation_probability?.[i])+'%'],['🌡️ Temperature',n(c.temperature_2m).toFixed(0)+' °C'],['💨 Wind',n(c.wind_speed_10m).toFixed(0)+' km/h'],['💦 Humidity',n(c.relative_humidity_2m).toFixed(0)+'%'],['⛈️ CAPE',n(h.cape?.[i]).toFixed(0)+' J/kg'],['🌬️ Gust',n(c.wind_gusts_10m).toFixed(0)+' km/h'],['☁️ Cloud',n(c.cloud_cover).toFixed(0)+'%']];$('current').innerHTML=vals.map(x=>'<div class="card"><div class="label">'+x[0]+'</div><div class="value">'+x[1]+'</div></div>').join('')}
function hours(d){const h=d.hourly;let a='';for(let i=0;i<10;i++){const dt=new Date(h.time[i]);a+=`<div class="hour"><b>${dt.toLocaleTimeString('en-IN',{hour:'numeric',minute:'2-digit'})}</b><strong>${mm(h.precipitation[i])} mm</strong><small>Rain ${n(h.precipitation_probability[i])}%</small><small>${n(h.weather_code[i])>=95?'⚡ Thunder':'🌦️ Rain/Cloud'}</small></div>`}$('hours').innerHTML=a}
async function forecast(model){const q=new URLSearchParams({latitude:LAT,longitude:LON,hourly:'precipitation,precipitation_probability,weather_code,temperature_2m,wind_gusts_10m,cape',forecast_days:3,timezone:'Asia/Kolkata'});if(model)q.set('models',model);return getJSON(OM+'?'+q)}
async function load(){try{$('headline').textContent='Fetching radar, nowcast and independent weather models…';weather=await forecast();cards(weather);hours(weather);const models=[['ECMWF','ecmwf_ifs025'],['GFS','gfs_seamless'],['ICON','icon_global'],['AIFS','ecmwf_aifs025']];const out=await Promise.all(models.map(async x=>{try{return [x[0],await forecast(x[1])]}catch(e){return [x[0],null]}}));let rows=out.map(([name,d])=>{const rain=n(d?.hourly?.precipitation?.slice(0,10).reduce((a,b)=>a+n(b),0));return {name,rain}});$('models').innerHTML=rows.map(x=>`<div class="model"><b>${x.name}</b><div class="rain">${mm(x.rain)} mm</div><small>next 10h model rainfall</small></div>`).join('');const spread=Math.max(...rows.map(x=>x.rain))-Math.min(...rows.map(x=>x.rain));$('confidence').textContent=spread<2?'High':spread<6?'Medium':'Low';$('headline').textContent=rainSentence(weather);await radar();await warnings();news(rows)}catch(e){console.error(e);$('headline').textContent='Data temporarily unavailable — tap Refresh.'}}
function rainSentence(d){const p=Math.max(...(d.hourly.precipitation_probability||[]).slice(0,10).map(n));const r=(d.hourly.precipitation||[]).slice(0,10).reduce((a,b)=>a+n(b),0);return r>0.5?`Next 10 hours: about ${mm(r)} mm forecast with peak rain chance ${p}%.`:p>=30?`Next 10 hours: rain chance reaches ${p}% around the selected window.`:'Next 10 hours: no significant model rainfall signal at Nagaur.'}
async function radar(){if(!map){map=L.map('map').setView([LAT,LON],8);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map);L.circle([LAT,LON],{radius:R*1000,color:'#1597bb',fill:false}).addTo(map);L.marker([LAT,LON]).addTo(map).bindPopup('Nagaur • 100 km watch area').openPopup()}try{const d=await getJSON('https://api.rainviewer.com/public/weather-maps.json?ts='+Date.now());const f=d?.radar?.past?.slice(-8)||[];radarLayers.forEach(x=>map.removeLayer(x));radarLayers=f.map(x=>L.tileLayer(d.host+x.path+'/256/{z}/{x}/{y}/2/1_1.png',{opacity:.0,attribution:'Weather data by RainViewer'}).addTo(map));if(radarLayers.length){radarLayers[radarLayers.length-1].setOpacity(.65);$('radarStatus').textContent='Live radar loaded • '+new Date(f.at(-1).time*1000).toLocaleTimeString('en-IN')}else $('radarStatus').textContent='Radar coverage unavailable'}catch(e){$('radarStatus').textContent='Radar temporarily unavailable'}}
async function warnings(){try{const d=await getJSON(IMD+'warnings_district_api.php');const s=JSON.stringify(d).toLowerCase();$('warnings').textContent=s.includes('nagaur')? 'IMD district warning data received. Check official wording in source feed.':'IMD warning feed received; Nagaur-specific alert not detected in the returned payload.'}catch(e){$('warnings').textContent='IMD warning feed unavailable right now.'}}
function news(rows){const best=[...rows].sort((a,b)=>b.rain-a.rain);$('news').innerHTML='<div class="newsitem">📰 <b>Nagaur rain desk:</b> '+(weather?'Live model data loaded for the next 10 hours.':'Waiting for forecast.')+'</div><div class="newsitem">🌧️ <b>Model spread:</b> '+best.map(x=>x.name+' '+mm(x.rain)+' mm').join(' • ')+'</div><div class="newsitem">📡 <b>Nowcast:</b> Radar and short-term precipitation should be treated separately from model forecasts.</div>'}
$('refresh').onclick=load;load();setInterval(load,10*60*1000);