const LAT=27.202,LON=73.7339,RADIUS_KM=100;const TZ='Asia/Kolkata';const OM='https://api.open-meteo.com/v1/forecast';const IMD='https://mausam.imd.gov.in/api/';const MODELS=[['ECMWF','ecmwf_ifs025'],['GFS','gfs_seamless'],['ICON','icon_seamless'],['AIFS','ecmwf_aifs025']];let map,radarLayers=[],gridLayers=[],radarFrames=[],gridData=[],centerForecast,modelData=[],rainbowData=null,pystepsData=null;const $=id=>document.getElementById(id);const num=v=>Number.isFinite(Number(v))?Number(v):0;const one=v=>num(v).toFixed(1);const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
async function getJSON(url){const c=new AbortController(),t=setTimeout(()=>c.abort(),15000);try{const r=await fetch(url,{signal:c.signal,cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);return await r.json()}finally{clearTimeout(t)}}
function forecastUrl(lat=LAT,lon=LON,model=''){const q=new URLSearchParams({latitude:Array.isArray(lat)?lat.join(','):lat,longitude:Array.isArray(lon)?lon.join(','):lon,current:'temperature_2m,relative_humidity_2m,precipitation,rain,showers,weather_code,wind_speed_10m,wind_gusts_10m,cloud_cover',hourly:'precipitation,precipitation_probability,weather_code,temperature_2m,relative_humidity_2m,wind_speed_10m,wind_gusts_10m,cape,cloud_cover',forecast_hours:24,timezone:TZ,wind_speed_unit:'kmh',precipitation_unit:'mm'});if(model)q.set('models',model);return OM+'?'+q}
async function forecast(model=''){return getJSON(forecastUrl(LAT,LON,model))}
function currentCards(d){const c=d.current||{},h=d.hourly||{};const vals=[['🌧️ Rain now',one(c.precipitation)+' mm'],['💧 Rain chance',num(h.precipitation_probability?.[0])+'%'],['🌡️ Temperature',num(c.temperature_2m).toFixed(0)+' °C'],['💨 Wind',num(c.wind_speed_10m).toFixed(0)+' km/h'],['💦 Humidity',num(c.relative_humidity_2m).toFixed(0)+'%'],['⛈️ CAPE',num(h.cape?.[0]).toFixed(0)+' J/kg'],['🌬️ Gust',num(c.wind_gusts_10m).toFixed(0)+' km/h'],['☁️ Cloud',num(c.cloud_cover).toFixed(0)+'%']];$('current').innerHTML=vals.map(x=>'<div class="card"><div class="label">'+x[0]+'</div><div class="value">'+x[1]+'</div></div>').join('')}
function weatherIcon(code){code=num(code);return code>=95?'⚡':code>=80?'🌧️':code>=50?'🌦️':code>=1?'⛅':'☀️'}
function renderHours(d,active=0){const h=d.hourly;if(!h?.time)return;$('hours').innerHTML=h.time.slice(0,10).map((t,i)=>{const dt=new Date(t);return '<div class="hour '+(i===active?'active':'')+'"><b>'+dt.toLocaleTimeString('en-IN',{hour:'numeric',minute:'2-digit'})+'</b><strong>'+weatherIcon(h.weather_code[i])+' '+one(h.precipitation[i])+' mm</strong><small>Rain '+num(h.precipitation_probability[i])+'%</small><small>'+num(h.temperature_2m[i]).toFixed(0)+'°C • '+num(h.wind_speed_10m[i]).toFixed(0)+' km/h</small></div>'}).join('')}
function gridPoints(){const pts=[];for(let y=-4;y<=4;y++)for(let x=-4;x<=4;x++){const lat=LAT+y*0.225,lon=LON+x*0.245;const dy=(lat-LAT)*111,dx=(lon-LON)*111*Math.cos(LAT*Math.PI/180);if(Math.hypot(dx,dy)<=100)pts.push({lat,lon})}return pts}
function gridRain(g,i){return num(g?.hourly?.precipitation?.[i])}
async function loadGrid(){const pts=gridPoints();const lats=pts.map(p=>p.lat),lons=pts.map(p=>p.lon);const d=await getJSON(forecastUrl(lats,lons,'ecmwf_ifs025'));const arr=Array.isArray(d)?d:[d];gridData=pts.map((p,i)=>({p,g:arr[i]||null}));renderGrid(0);renderRegional();return gridData}
function rainClass(mm){return mm<0.05?'l0':mm<1?'l1':mm<5?'l2':mm<15?'l3':'l4'}
function rainColor(mm){return mm<0.05?'#b8c9d2':mm<1?'#6cc5e8':mm<5?'#45b889':mm<15?'#f0b429':'#e05252'}
function renderGrid(hour){gridLayers.forEach(x=>map.removeLayer(x));gridLayers=[];if(!gridData.length)return;for(const item of gridData){const rain=gridRain(item.g,hour);const c=L.circleMarker([item.p.lat,item.p.lon],{radius:8,weight:1,color:'#fff',fillColor:rainColor(rain),fillOpacity:0.72}).bindPopup('<b>'+item.p.lat.toFixed(2)+', '+item.p.lon.toFixed(2)+'</b><br>Forecast hour +'+hour+'<br><b>'+one(rain)+' mm</b> rain');gridLayers.push(c);c.addTo(map)}$('timeLabel').textContent=hour===0?'Now':'+'+hour+'h';$('timeSlider').value=hour;renderHours(centerForecast,hour)}
function renderRegional(){const sorted=gridData.map(x=>({lat:x.p.lat,lon:x.p.lon,total:(x.g?.hourly?.precipitation||[]).slice(0,10).reduce((a,b)=>a+num(b),0),peak:Math.max(...(x.g?.hourly?.precipitation||[]).slice(0,10).map(num),0)})).sort((a,b)=>b.total-a.total);$('regional').innerHTML=sorted.slice(0,12).map((x,i)=>'<div class="region"><b>#'+(i+1)+' hotspot</b><div class="rain">'+one(x.total)+' mm / 10h</div><div class="sub">Peak hour: '+one(x.peak)+' mm</div><div class="sub">'+x.lat.toFixed(2)+'°, '+x.lon.toFixed(2)+'°</div></div>').join('')}
function modelCard(name,d){const h=d?.hourly||{};const rain=(h.precipitation||[]).slice(0,10).reduce((a,b)=>a+num(b),0);const probs=(h.precipitation_probability||[]).slice(0,10);const peak=Math.max(...probs.map(num),0);return {name,rain,peak,d}}
async function loadModels(){const out=await Promise.all(MODELS.map(async m=>{try{return modelCard(m[0],await forecast(m[1]))}catch(e){return {name:m[0],rain:null,peak:null,d:null}}}));modelData=out;const valid=out.filter(x=>x.rain!==null);const rains=valid.map(x=>x.rain);const mean=rains.reduce((a,b)=>a+b,0)/(rains.length||1);const spread=(Math.max(...rains,0)-Math.min(...rains,0));const agreement=clamp(Math.round(100/(1+spread/Math.max(mean,1))),0,100);$('confidence').textContent=agreement+'%';$('models').innerHTML=out.map(x=>'<div class="model"><b>'+x.name+'</b><div class="rain">'+(x.rain===null?'Unavailable':one(x.rain)+' mm')+'</div><div class="sub">Peak rain chance: '+(x.peak===null?'—':x.peak+'%')+'</div><div class="sub">Next 10h model total</div></div>').join('');return out}
function consensusSentence(){const h=centerForecast?.hourly;if(!h)return 'Forecast data unavailable.';const total=(h.precipitation||[]).slice(0,10).reduce((a,b)=>a+num(b),0);const p=Math.max(...(h.precipitation_probability||[]).slice(0,10).map(num),0);if(total>=15)return 'Heavy rain signal in the next 10 hours; use the map to see where the regional model places the strongest cells.';if(total>=5)return 'A meaningful rain signal is present in the next 10 hours; timing and location can shift between model runs.';if(p>=30)return 'Some rain potential is present, but the amount signal is limited; watch radar history and model spread.';return 'No strong model rainfall signal at Nagaur in the next 10 hours.'}
function initMap(){if(map)return;map=L.map('map').setView([LAT,LON],8);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map);L.circle([LAT,LON],{radius:RADIUS_KM*1000,color:'#1597bb',fill:false,weight:2}).addTo(map);L.marker([LAT,LON]).addTo(map).bindPopup('<b>Nagaur</b><br>100 km watch radius');document.querySelectorAll('.tool').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tool').forEach(x=>x.classList.remove('active'));b.classList.add('active');const mode=b.dataset.layer;radarLayers.forEach(x=>x.setOpacity(mode==='grid'?0:0.65));gridLayers.forEach(x=>x.setStyle({opacity:mode==='radar'?0:1,fillOpacity:mode==='radar'?0:0.72}))})}
async function loadRadar(){initMap();try{const d=await getJSON('https://api.rainviewer.com/public/weather-maps.json?ts='+Date.now());radarFrames=d?.radar?.past||[];radarLayers.forEach(x=>map.removeLayer(x));radarLayers=radarFrames.slice(-12).map(f=>L.tileLayer(d.host+f.path+'/256/{z}/{x}/{y}/2/1_1.png',{opacity:0,attribution:'Weather data by RainViewer'}).addTo(map));$('radarSlider').max=Math.max(radarLayers.length-1,0);$('radarSlider').value=Math.max(radarLayers.length-1,0);setRadarFrame(radarLayers.length-1);$('radarStatus').textContent=radarLayers.length?'Radar history loaded • '+new Date(radarFrames.at(-1).time*1000).toLocaleTimeString('en-IN'):'Radar history unavailable'}catch(e){$('radarStatus').textContent='Radar temporarily unavailable'}}
function setRadarFrame(i){radarLayers.forEach((x,k)=>x.setOpacity(k===Number(i)?0.68:0));const f=radarFrames[Math.max(0,radarFrames.length-radarLayers.length+Number(i))];$('radarLabel').textContent=f?new Date(f.time*1000).toLocaleTimeString('en-IN',{hour:'numeric',minute:'2-digit'}):'—'}
async function loadIMD(){try{const [w,nc,rf]=await Promise.all([getJSON(IMD+'warnings_district_api.php'),getJSON(IMD+'nowcast_district_api.php?id=5'),getJSON(IMD+'districtwise_rainfall_api.php')]);const text=(JSON.stringify(w)+' '+JSON.stringify(nc)+' '+JSON.stringify(rf)).toLowerCase();const pos=text.indexOf('nagaur');let excerpt=pos>=0?text.slice(Math.max(0,pos-180),Math.min(text.length,pos+520)):'Nagaur was not found by a simple text match in the returned district feeds.';$('warnings').innerHTML='<div class="newsitem"><b>IMD feeds:</b> warning, district nowcast and district rainfall endpoints responded.</div><div class="sub">Nagaur text check: '+(pos>=0?'found':'not found')+'</div><details><summary>Returned Nagaur-area excerpt</summary><pre>'+excerpt.replace(/[<>]/g,'')+'</pre></details>'}catch(e){$('warnings').textContent='IMD district feeds temporarily unavailable; the map and model forecast remain separate.'}}
function renderVerification(){const vals=modelData.filter(x=>x.d);$('verification').innerHTML='<div class="verifybox"><b>'+vals.length+'/4</b><div>models returned data</div></div><div class="verifybox"><b>0%</b><div>unmeasured accuracy claims</div></div><div class="verifybox"><b>Ready</b><div>forecast-vs-observation framework</div></div><div class="verifybox"><b>Next</b><div>store forecast snapshots + IMD observed rain before publishing measured scores</div></div>'}
function renderPysteps(){
  const box=$('pystepsNowcast');
  if(!pystepsData || !Array.isArray(pystepsData.summary) || !pystepsData.summary.length){
    $('pystepsStatus').textContent='Waiting for quantitative radar';
    box.innerHTML='<div class="newsitem">pySTEPS engine is installed and ready, but it needs quantitative radar frames (NetCDF/HDF5/GeoTIFF). Visual/colorized map tiles are not treated as quantitative radar input.</div>';
    return;
  }
  $('pystepsStatus').textContent='pySTEPS • '+pystepsData.lead_minutes+' min';
  box.innerHTML=pystepsData.summary.slice(0,12).map(x=>{
    return '<div class="nc"><b>+'+x.lead_minutes+'m</b><strong>'+num(x.center_mm_h).toFixed(2)+'</strong><small>mm/h center</small></div>';
  }).join('');
}
async function loadPysteps(){
  try{
    const r=await fetch('data/pysteps-nowcast.json?ts='+Date.now(),{cache:'no-store'});
    if(!r.ok)throw Error(r.status);
    pystepsData=await r.json();
  }catch(e){pystepsData=null}
  renderPysteps();
}
function renderRainbow(){const box=$('rainbowNowcast');if(!rainbowData?.forecast?.length){$('rainbowStatus').textContent='Waiting for Rainbow API key';box.innerHTML='<div class="newsitem">Rainbow AI integration is installed, but the API key must be stored as a GitHub Actions secret named <b>RAINBOW_API_KEY</b>. Until then the dashboard continues with radar + model data.</div>';return}$('rainbowStatus').textContent='Rainbow AI • 0–4h';const f=rainbowData.forecast.slice(0,24);box.innerHTML=f.map((x,i)=>{const t=new Date(x.timestampBegin*1000).toLocaleTimeString('en-IN',{hour:'numeric',minute:'2-digit'});return '<div class="nc"><b>'+t+'</b><strong>'+num(x.precipRate).toFixed(2)+'</strong><small>mm/h</small></div>'}).join('')}\nasync function loadRainbow(){try{const r=await fetch('data/rainbow-nowcast.json?ts='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error(r.status);rainbowData=await r.json();renderRainbow()}catch(e){rainbowData=null;renderRainbow()}}\nfunction renderNews(){const valid=modelData.filter(x=>x.rain!==null);const ranking=[...valid].sort((a,b)=>b.rain-a.rain);$('news').innerHTML='<div class="newsitem">🌧️ <b>Nagaur rain desk:</b> '+consensusSentence()+'</div><div class="newsitem">📐 <b>Model spread:</b> '+ranking.map(x=>x.name+' '+one(x.rain)+' mm').join(' • ')+'</div><div class="newsitem">📡 <b>Radar:</b> the public RainViewer feed currently provides observed past radar frames; future nowcast frames are not assumed from the API.</div><div class="newsitem">🧭 <b>Regional watch:</b> the grid uses 81 points inside the 100 km circle and can be scrubbed hour-by-hour.</div>'}
async function load(){const btn=$('refresh');btn.disabled=true;btn.textContent='Updating…';try{$('headline').textContent='Fetching live weather, radar and regional models…';const [base]=await Promise.all([forecast(),loadRadar(),loadRainbow(),loadPysteps()]);centerForecast=base;currentCards(base);renderHours(base);$('headline').textContent=consensusSentence();$('updated').textContent='Updated '+new Date().toLocaleString('en-IN');await Promise.all([loadModels(),loadGrid(),loadIMD()]);renderRainbow();renderPysteps();renderNews();renderVerification()}catch(e){console.error(e);$('headline').textContent='Some data sources are temporarily unavailable. Tap Refresh to retry.'}finally{btn.disabled=false;btn.textContent='↻ Refresh'}}
$('refresh').onclick=load;$('timeSlider').oninput=e=>renderGrid(Number(e.target.value));$('radarSlider').oninput=e=>setRadarFrame(Number(e.target.value));initMap();load();setInterval(load,10*60*1000);
